name: rally_fotografico
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - lib/assets/

flutter_launcher_icons:
  android: "launcher_icon" # Name for Android icon
  ios: true # Enable iOS icon generation
  image_path: "lib/assets/logo.png" # Path to your 1024x1024 icon
  min_sdk_android: 21 # Optional: Minimum Android SDK
  remove_alpha_ios: true # Optional: Remove alpha channel for iOS
  adaptive_icon_background: "#FFFFFF" # Optional: Android adaptive icon background color