/**
 * Opciones de configuración de Firebase generadas automáticamente.
 * No modificar manualmente este archivo.
 * @author Alberto Cárdeno
 */
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
// Comentario: Clase DefaultFirebaseOptions para obtener la configuración según la plataforma.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcYdML1B9lkCKS2HUgB_CzOY9hc0-qc9k',
    appId: '1:202650214430:web:b2932c3f5257771b428e0f',
    messagingSenderId: '202650214430',
    projectId: 'rallyfotografico-b9f0d',
    authDomain: 'rallyfotografico-b9f0d.firebaseapp.com',
    storageBucket: 'rallyfotografico-b9f0d.firebasestorage.app',
    measurementId: 'G-TYTZ0PVRTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCMpXjCJtDmOOjWvd1hTRdk7ZVnjHOb6k',
    appId: '1:202650214430:android:72b86f8db505461d428e0f',
    messagingSenderId: '202650214430',
    projectId: 'rallyfotografico-b9f0d',
    storageBucket: 'rallyfotografico-b9f0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAaed57TN4w9rekCgzz3l_4nFvJdu_yzA',
    appId: '1:202650214430:ios:600aad4650b3c004428e0f',
    messagingSenderId: '202650214430',
    projectId: 'rallyfotografico-b9f0d',
    storageBucket: 'rallyfotografico-b9f0d.firebasestorage.app',
    iosBundleId: 'com.example.rallyFotografico',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAaed57TN4w9rekCgzz3l_4nFvJdu_yzA',
    appId: '1:202650214430:ios:600aad4650b3c004428e0f',
    messagingSenderId: '202650214430',
    projectId: 'rallyfotografico-b9f0d',
    storageBucket: 'rallyfotografico-b9f0d.firebasestorage.app',
    iosBundleId: 'com.example.rallyFotografico',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcYdML1B9lkCKS2HUgB_CzOY9hc0-qc9k',
    appId: '1:202650214430:web:db5137b6ee98f77c428e0f',
    messagingSenderId: '202650214430',
    projectId: 'rallyfotografico-b9f0d',
    authDomain: 'rallyfotografico-b9f0d.firebaseapp.com',
    storageBucket: 'rallyfotografico-b9f0d.firebasestorage.app',
    measurementId: 'G-F7NQQCCJ0K',
  );

}